remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Disha Devalkar
description: >
Final-year Information Technology Engineering student graduating in 2026
with a strong interest in software development, frontend technologies,
and problem-solving. Skilled in working with modern digital tools and
technologies including React, JavaScript, HTML, CSS, Canva,
Microsoft Excel, and PowerPoint.

Passionate about building user-friendly applications and continuously
learning new technologies.

An active and confident individual with good communication, teamwork,
and coordination skills gained through academic projects, presentations,
and college activities.

Known for being adaptable, creative, and quick to learn.Interested in
opportunities that encourage innovation, collaboration, and professional
growth in the tech industry.
